### ISSUE TITLE
Checkout from a Mexico IP causes foreignCurrencyCode issue

### ISSUE THREAD

**Issue by brossetti1** [Ryanair/localisation-service#1]
Hey all,

just booked a flight from Mexico and ran into some troubles on the last part of checkout. steps to reprodue:

1) connected to Mexico IP
2) go to final cart checkout page
3) type in credit card number 

after the credit card number is typed in - the `currency-converter.payment-methods__currency-converter` fails with an unresolved error:

```
ERROR TypeError: Cannot read properties of null (reading 'foreignCurrencyCode')
```

i replicated this on both chrome and firefox (where i have no plugins) - the url this is occuring on is `https://www.ryanair.com/gb/en/payment` - when this dropdown fails - you cannot finish the checkout process.

I resolved this error and was able to purchase my ticket only after I logged onto my **VPN and specified a US ip address (makes sense that the US ip would resolve to USD)** - just wanted to report this while it was fresh in my mind as you might have alot of customers that are not going through the resolution process when they are trying to book flights FROM Mexico. 

<img width="1400" alt="Screen Shot 2021-10-09 at 5 06 34 PM" src="https://user-images.githubusercontent.com/5998100/136675061-f9d3d15f-6439-48ff-9e17-66114616a434.png">

**Comment by brossetti1** [comment]
old repo... whoops

**Comment by brossetti1** [comment]
old repo... whoops

**Comment by alexpilotti** [comment]
Same issue from a Romanian IP
